### ISSUE TITLE
Make "Add Library" a search field with autosuggest dropdown 

### ISSUE THREAD

**Issue by sbussard** [jsbin/jsbin#2723] opened 2016-03-08 14:22 UTC
Make "Add Library" a search field with autosuggest dropdown

I imagine it to look like spotlight search in Mac El Capitan (cmd + space bar)

**Comment by remy** [comment] 2016-03-08 20:56
Dupe of https://github.com/jsbin/jsbin/pull/2531 - in progress (albeit idle)

**Closed by remy** 2016-03-08 20:56 UTC
