### ISSUE TITLE
Can not log in my Jsbin account 

### ISSUE THREAD

**Issue by sunlight200** [jsbin/jsbin#3050] opened 2017-05-12 23:09 UTC
I try to log to my jsbin account using my Github account but It cant redirected me to my account ,I tried to clear my browser cookies lots of times but I still have the problem ,any suggestion to solve it 
here is a screenshot of it 
http://prntscr.com/f7765p

**Comment by remy** [comment] 2017-05-13 06:53
Dupe of #3045

**Closed by remy** 2017-05-13 06:53 UTC
