### ISSUE TITLE
document.body.innerHTML returns unwanted script content

### ISSUE THREAD

**Issue by impressivewebs** [jsbin/jsbin#2610] opened 2015-11-05 08:43 UTC
[See this demo](https://jsbin.com/gowiwu/edit?html,css,js,console,output)

The log should output whatever I have inside the body in the HTML panel, but it's also adding a JSBin-specific script, so the output looks like this:

```html
"
  <p>This is some <b>example text</b></p>
<script>try {window.runnerWindow.proxyConsole.log(document.body.innerHTML);
} catch (error) { throw error; }

//# sourceURL=gowiwu.js
</script>"
```

It should look like this:

```html
"
  <p>This is some <b>example text</b></p>
"
```

Same result with `textContent` (but with HTML stripped out), but `innerText` works fine, (which is probably due to the fact that `innerText` doesn't grab the content of scripts, IIRC).

**Comment by remy** [comment] 2015-11-05 08:49
You're seeing inside of jsbin runner harness. This doesn't get applied when you're in the full output but it's part of jsbin in the editor.

The same with jsbin's rewriting of the console.log code, which is required to hook into the custom console.

Closing because its not a bug that I can make any changes to, sorry (without the harness, jsbin blows up in a few places).

**Closed by remy** 2015-11-05 08:49 UTC

**Comment by impressivewebs** [comment] 2015-11-05 09:11
Ah ok, yes, it works correctly in output mode. Thanks.
