### ISSUE TITLE
https://jsbin.com/account/editor url redirects indefinitely

### ISSUE THREAD

**Issue by jazzominy** [jsbin/jsbin#3288] opened 2018-10-25 06:55 UTC
When navigating to Editor Settings or Preferences from Accounts menu, the redirecting does not work as expected. It keeps on redirecting indefinitely. This happens in Chrome and Firefox. The browser (Chrome) error is attached for reference

![image](https://user-images.githubusercontent.com/1888304/47481345-cc20f600-d822-11e8-98b3-41d993807c1b.png)

**Comment by remy** [comment] 2018-10-25 07:06
Dupe of #3283.

**Closed by remy** 2018-10-25 07:06 UTC

**Comment by jazzominy** [comment] 2018-10-25 07:35
Extremely sorry I did't go through the list of open issue 🙏
