### ISSUE TITLE
Can't login via Github

### ISSUE THREAD

**Issue by Imiszkusz** [jsbin/jsbin#3053] opened 2017-05-14 07:38 UTC
Hello,

I am not able to log in Jsbin anymore using the 'login with Github' option.
No matter if i am logged in to Github or not, the yellow 'login or register' button remains there when I try to use that option.
I even tried that I logged off github and so I had to enter my github credentials in jsbin interface, it still results in the same - nothing changes, i am not logged in, the yellow button remains there.

thanks in advance for any help

**Comment by remy** [comment] 2017-05-14 08:55
Dupe of #3045

**Closed by remy** 2017-05-14 08:55 UTC
