### ISSUE TITLE
Problem to upgrade in Pro account

### ISSUE THREAD

**Issue by srayy** [jsbin/jsbin#3118] opened 2017-09-15 10:57 UTC
Want to upgrade in Pro account, after filling details of credit card and press upgrade to confirm it shows forbidden! Please help us to access pro account.
Thanking you.
With regards
Bidhan Chattrerjee.
[on behalf of w3resource.com] 
Note: Can we get some concession (monthly/yearly) as we use jsbin at w3resource.com (completely free)  purely education and learning purpose and we maintain Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.

**Comment by remy** [comment] 2017-09-26 06:55
Dupe of #3072

**Closed by remy** 2017-09-26 06:55 UTC
