### ISSUE TITLE
codecasting no longer works

### ISSUE THREAD

**Issue by b2mgithub** [jsbin/jsbin#2800] opened 2016-06-30 08:50 UTC
i cannot seem to get the codecasting to work, no matter what i try.
putting the username in the url, latest, last and watch all give me an error.
i read the article on new short urls and followed along and used the share.
any suggestions?

**Comment by francoisp** [comment] 2016-07-19 23:12
is this on a local installation or on the live production website? I have the same behaviour on a local installation, but when I open two anonymous edits on the jsbin.com website it works fine.

**Comment by remy** [comment] 2016-07-20 08:50
This was fixed in this: https://github.com/jsbin/jsbin/commit/c2a781ebbac3515bee8a661066e01902bbd25463

@francoisp thanks for commenting on these issues, it's helping me close them up 👍

**Closed by remy** 2016-07-20 08:50 UTC

**Comment by b2mgithub** [comment] 2016-07-20 22:23
francois,

my question was about the live production site logged on with my pro
account (b2mgithub).
i was trying to use the urls like this link https://jsbin.com/blog/urls
or follow along with the youtube
https://www.youtube.com/watch?v=PHDThjUOJSc&list=PLXmT1r4krsTooRDWOrIu23P3SEZ3luIUq&index=12
none of it seems to work with my account.
i cant put my username in the url, watch, latest, auto codecast on edit,
none of it works.

i did get a support email that it was fixed, but not really.
i missed the deadline on my project, and had to use something else.
this issue has been closed, but still doesn't work for me at all.
just try to follow along with the youtube video.

ps after all this i managed to get a local version installed on windows
(older version).
added a little cors support, some parent window iframe messaging in the
runner, integrated some kendo ui, and store my project in sql server.
the end result is a super easy way to store and manage a bunch of codecast
items (with meaningful names) as an tree (outline) for teaching a course.
and zero time spent managing urls or versions.

bart

**Comment by francoisp** [comment] 2016-07-20 22:44
Hello Bart,

sorry to hear that. I’ve just recently come across jsbin; really cool project, it’s awesome that it is MIT licensed, I can’t believe its been around for so long and I never looked at it before. 
 I’m planning on using parts of the code for something else. I ran in a similar issue, but it must not be the same. On the live production website, I can simply copy and paste the url of a recently created anonymous bin is a different browser (say ff and chrome) and updates from the first window “codecast”  to the second window, I believe this is spike.js code based EventSource.js that’s doing its trick. 

On a local install, this does not work. Even worse, after creating a test bin in say chrome, then going to the same url in ff, updating the original in chrome, I see the new bin being posted to the db, but “browser refresh” does not even reload the change in the second browser.

best regards,
F

**Comment by remy** [comment] 2016-07-21 07:19
On the code casting, your issue said no matter what you try, and I was able to replicate at the time, identify the bug and fix it.

Here's a screencast of code casting I took this morning:

![codecast mp4](https://cloud.githubusercontent.com/assets/13700/17014179/113ebd46-4f1b-11e6-94b5-80b1f18bf89a.gif)

I'm casting from Chrome to Firefox over jsbin.com. Note that the gif is playing at 2x speed, but I also had a laggy connection at the time. Note that I create a new bin in Chrome, I copy the URL from the address bar. This is all that's required for codecasting. 

To live render, I can repeat the same process, except I *remove* the `/edit` from the URL before loading in Firefox (note that this is unrelated to the issue you raised, but I've included it for completeness):

![cast mp4](https://cloud.githubusercontent.com/assets/13700/17014265/9b248734-4f1b-11e6-9a70-4c3f80475778.gif)

Regarding local installs – I'm running from a local install to do all my development (which is how I fixed the issue), but to be very clear: a) there is no support for local installs because it's constantly in flux, and b) the npm version is utterly out of date.

All of this has nothing to do with pro account features (just to clarify).

I *think* there's a hidden issue in what you've filed. I *believe* the issue is actually this:

- Create a new bin with a logged in account
- Open jsbin.com/<user>/last/
- This loads the correct content, but I believe that the live rendering doesn't work

This is a separate issue that should be raised, but importantly can be easily worked around by sharing the *real* URL of the bin.

Let me know if this is correct and we can open a new issue with those details.

**Comment by b2mgithub** [comment] 2016-07-21 09:02
Remy,

I keep mentioning the pro account because I need to log in to save my
collection of finely tuned bins I want to use for codecasting.
You could make it work, but I could not, so I dug a little deeper and made
a chart of my findings.
[image: Inline image 1]
I attached a fast forward video called support.mp4 of the 6 tests matching
the chart above.
Obviously I was constantly trying the 4 that don't work for me, and not the
2 that do.
I now agree that it is fixed and you can close my support question.

On a side note, I did manage to get it to work locally.
After a few days of fiddling with cors and iframe parent messages from the
runner because I couldn't make it work on port 80 I came up with a solution
for using jsbin to teach a local coding for kids course in northern rural
canada.
I also attached a fast forward video called jsbin.mp4 that shows a
simplified version.

I would have made fancy gifs like you, but the file size and frame rate was
too high.

Regards,
Bart

**Comment by b2mgithub** [comment] 2016-07-21 09:23
Francois,

I have been back and forth a few times with remy on the codecasting issue.
The confusion was that i need to be logged in (have a pro account) to save
my fine tuned bins for codecasting during a coding for kids course in
northern rural bc canada.
Here is the results of my more careful testing.
[image: Inline image 1]
We are actually building a platform for the new bc school curriculum which
is based on signalr (ms version of sockets and long polling).
Sort of two way slack style messaging / codecasting the entire content
(including coding samples), with bots (as teaching assistants) and quizzes
(maybe gamification and web based dynamic ar in the future).
No attempt to solicit or stalk you, but attached a fast forward video of
how we are using jsbin.
Hope you get yours all working locally, it is a real puzzler.

Regards,
Bart

**Comment by remy** [comment] 2016-07-21 10:45
The images didn't attach (suspect github doesn't support then via emails). Can you upload them to the thread on github and I can take a closer look.

I don't doubt you're experiencing this problem, it's that since the fix referred to earlier, I can't replicate (which I'm keen to do - please be reassured that I don't intend to brush you away! ☺).

I'll take a look later today if you're able to upload your screenshots you took.

Cheers.

**Comment by b2mgithub** [comment] 2016-07-21 11:04
Remy,

I put the the videos in a sample folder on my server instead.
The links are...
chart
<http://ppa.business2mobile.com/desktopmodules/PPALocal/App2/Northwind/videos/chart.png>
support
<http://ppa.business2mobile.com/desktopmodules/PPALocal/App2/Northwind/videos/support.mp4>
jsbin
<http://ppa.business2mobile.com/desktopmodules/PPALocal/App2/Northwind/videos/jsbin.png>
concept

Bart

**Comment by b2mgithub** [comment] 2016-07-21 11:08
Francois,

The support part of jsbin does not allow attachments.
So here is the full links to the files discussed.
chart
<http://ppa.business2mobile.com/desktopmodules/PPALocal/App2/Northwind/videos/chart.png>
jsbin
<http://ppa.business2mobile.com/desktopmodules/PPALocal/App2/Northwind/videos/jsbin.png>
 concept

Regards,

Bart

**Comment by francoisp** [comment] 2016-07-21 12:20
Hey Bart, fellow Canadian eh? :-) cheers!

I looked at your video, I had only tried a few of these configs, but none worked. Looking at the code I don't see that pro has a bearing, but the live var in feature.js has to be true, or else the casting code (spike.js) will not even be included, see partials/index.html at the bottom.

Cool project. Im planning on using this code base for something else, integrating a SQL playground as well, running in a dynamic unprivileged lxc container. 

When I first came across this, a project in the dynamic teaching with samples --pre framed problems and unit tests for autonomous learning is the first idea that came to mind. I have 5 kids, the oldest being 10, which is the about the age I started to get into programming. The gaming world was a lot less interactive back then. I'm very keen on getting them to code asap, as least the 2 older ones, to show them there is world out there besides clashing clans and chasing pokemons. To spark their interest it has to be dynamic. Jsbin seems like a perfect tool for this.

I fixed the port of socket.io for iOS, a few years back, before they released the swift implementation. I might try to plug socket.io in place of the eventlistener.js locally, at first glance I think this is where this problem is. 

Whats extra puzzling is that reloading the page after clearing the cache will not even reload the changes in the second browser! 

Way way back (2011) when I still had stuff in csharp on iis I used signalr. I remember it scaled surprisingly well.

Cheers!
F

**Comment by francoisp** [comment] 2016-07-21 14:43
actually it’s in handlers/bin.js that the live flag is defined. If you look at lib/routes.js around 894 in the latest code on github, you’ll see that this get sets to true on the server side in the req obj if the url is ‘/watch’. So in the code I have, unless the second url is watch, spike.js is not included. BUT there’s a long poll request pending in the browser even when this file is not included. I wondered if there was another notification mechanism but looking at the production jsbin.com, I see that the /js/spike.js is loaded on the second browser that opens an anon bin, i believe its triggered in js/chrome/infocard.js, even if the url does not contain ‘/watch’, a behaviour that does not occur local. (spike.js get’s loaded on local only if you have ‘/watch’ in the url.) The dynamic presence of this code, and the doc that says codecast uses this spike mechanism leads me to believe this is still the way the message gets across. 

spike loaded or not, it looks like there’s no event fired so the bin changes do not propagate; what’s more, clearing the cache and reloading on this second browser does not even get the up to date bin; I see a request go through in the db for the latest, but I still get the initial loaded bin rendered in this second browser. How this gets cached past the reload and cache clean is really a puzzle.

best,
F

**Comment by francoisp** [comment] 2016-07-21 15:14
>  How this gets cached past the reload and cache clean is really a puzzle.

FYI, I found how this was occurring. In jsbin.js around 311 there’s code executed on unload. So when I reload the page this gets executed before reload, and the content is saved to the session then restored to the page. When I clean the cache, the session and the page gets trashed, but because the page is still open, the javascript is still in the v8 instance, in chrome. When I reload the url, this unload code get’s executed, bam, I get the old bin again. If I force jsbin.panels.saveOnExt to false, I then get the new bin. One less mystery. On to why the update event does not get fired across.

cheers,
F

**Comment by b2mgithub** [comment] 2016-07-21 19:06
Francois,

Since you were willing to watch my video and give a bit of feedback I am
sending you a live link to look at.
I need both editor and viewer to be able to be included (one is an iframe,
on is embedded) in our larger project.
So the urls end in "/latest/edit" and "/latest/watch".
Really all you need is a nested tree navigation that knows the three letter
url, it will use the latest bin, and you can ignore revisions.
Here is the link to the simple jsbin manager
<http://ppa.business2mobile.com/desktopmodules/PPALocal/App2/Francois/TestJSBins.html>,
it should work in chrome.

Also we have built what we call the B2M Industrial Kendo SPA Generator
<http://ppa.business2mobile.com/desktopmodules/PPALocal/App2/Francois/Demo.html>
.
I have some pretty far fetched ideas about endpoints,but for building
industrial applications it kicks ass.
And yes there is some microsoft, but that is what sells to resource
companies in our region.
It is also fast forward and vague, but it is a big topic.

I would be thrilled if you would give it a quick look and send me your
thoughts.

Bart

**Comment by francoisp** [comment] 2016-07-21 20:21
interesting project, Bart.

Well it turns out my problem was two-fold, spike.js was not getting loaded in the code I fetched from github a few days ago, and the nginx proxy was blocking the event stream.
so even with a fresh pull it still was not working, which led me to think something else was amiss.

these ngnix proxy settings fixed it with the latest code (3.38.1)

    proxy_set_header Connection '';
    proxy_http_version 1.1;
    chunked_transfer_encoding off;
    proxy_buffering off;
    proxy_cache off;

this hunt left me with a better understanding of how this works.

cheers,
F

**Comment by b2mgithub** [comment] 2016-07-21 20:47
Francois,

I never did get the proxy to work on my local copy.
I think you are supposed to set the url/host : website:80 (which conflicts
for me when running alongside iis)
Then when you start it up with a command prompt you send $port=8080 jsbin
(which overrides the config setting)?

My way around this was to have a page at :80, and an iframe to :8080 which
is cross domain.
To pass stuff to the parent page so I could update my sql project I used
window.addEventListener and added the following to runner.js

var state = runner.parent["source"]["jsbin"]["state"];
window.top.postMessage(JSON.stringify(state), '*');

This allows the jsbin iframe to send stuff to the parent page every time it
saves.

Then I added some 'Access-Control-Allow-Origin': '*' to the cors part of
middleware.js to allow the api to work.

If you get the nginx proxy to work on windows please tell me what you did.

Bart

**Comment by francoisp** [comment] 2016-07-21 20:59
Bart,
I’m not on widows. 

here are my nginx settings:
    proxy_set_header Host            \$host;
    proxy_set_header X-Real-IP       \$remote_addr;
#remove the next 2 if you are not over ssl
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header Connection '';
    proxy_http_version 1.1;
    chunked_transfer_encoding off;
    proxy_buffering off;
    proxy_cache off;

cheers,
F

**Comment by remy** [comment] 2016-07-22 06:08
@francoisp as much as I appreciate the contributions, can you both discuss offline configuration on another thread. There's a bunch of conversation in here that I'm unclear whether is right or wrong and really I want to close off whether code casting is working or not. Cheers.

@b2mgithub I appreciate the video, but I can't actually tell what the situation is when code casting fails. Can you reupload but at normal speed? Or even better, isolate the failing example and show the process starting with an empty browser (don't skip the initial creation).

I also see you're trying to test code casting from the same window (where you make the change in one tab, then move to another tab). This isn't code casting, and the when the tab is hidden, the code casting turns off. If you want to test chrome to chrome (for instance) you need two windows, not two tabs (I can go into technical reasons why I don't cast to the out of focus tab if you want).

Final note, you mentioned "jsbin support doesn't…"—in case you weren't aware (and it's likely you are), this conversation is happening on github, not jsbin: https://github.com/jsbin/jsbin/issues/2800

Thanks. Looking forward to seeing the updated examples.

– Remy

**Comment by remy** [comment] 2016-07-22 06:10
Oh, one thing I picked up from your issue comments: you're using `/watch` on the URL. Don't. I've been meaning to remove this entirely. Code casting is built into the `/edit` URL (watch is legacy and will be removed, no functionality will be lost).

**Comment by francoisp** [comment] 2016-07-22 07:04
@remy terribly sorry, was unaware you and github were still in the loop. Code cast now works fine for me, local, behind a proxy over ssl. These 4 additional settings are required for the x-stream updates of EventSource.js to go through the nginx proxy:     

    proxy_set_header Connection '';
    proxy_http_version 1.1;
    chunked_transfer_encoding off;
    proxy_buffering off;
    proxy_cache off;

Again, great project, thanks for releasing MIT. That other PR I pushed to github to store in a pgsql database got quite a few bug fixes along the way; I'll be using only that going forward,   

cheers,
F

**Comment by b2mgithub** [comment] 2016-07-22 07:38
@remy,

also sorry to have continued with this thread, am done with the cross talk
again go ahead and close the issue, it now works the way you demonstrated.

the fast forward video shows the same results as the chart in fast forward.
you can actually see two windows (or tabs) and chrome vs firefox and logged
on/not.
just trying to show i tried all the combinations listed.

in the end i found a great solution to my usage case, which is teaching a
half dozen kids simple coding in an rural farming town in northern canada.
even though i am using an older local version and did not completely solve
the nginx proxy on windows to be able to use port 80.
with a few lines of cors and a parent window message from the cross domain
bin it works great.
i can have a nested outline style tree of named examples, and a simple link
to edit or watch the latest one.
and it doesn't matter if i use two tabs in the same chrome browser.
i use ms signalr to edit while they watch and live push the desired bin to
all the kids laptops while teaching.
there is no versions or snapshots visible, and they can modify their own
bin.
when the course is over, i can run an sqlite script to reset the course
content.

will shut up now and get back to work.
thanks again,

bart

**Comment by remy** [comment] 2016-07-22 14:38
Ha. Good to hear on all fronts then! I was getting a bit confused there!

Thanks all.
