### ISSUE TITLE
I cant't load my javascript pages - error

### ISSUE THREAD

**Issue by dsolowiej** [jsbin/jsbin#3160] opened 2017-11-30 19:02 UTC
I recevied this post (when I try to read My Bins: "This page isn't here. How about heading back to the homepage instead? It's nice there and there are lots of things to click on. If you think there is supposed to be something here that isn't let us know via the Issues page". I see that there is 542 programs, but I can't read it. Please, help :)

**Comment by ggs692** [comment] 2017-12-01 02:38
I recevied this post (when I try to read My Bins: "This page isn't here. How about heading back to the homepage instead? It's nice there and there are lots of things to click on. If you think there is supposed to be something here that isn't let us know via the Issues page". I see that there is 542 programs, but I can't read it. Please, help :)

**Comment by ggs692** [comment] 2017-12-01 02:40
I recevied this post (when I try to read My Bins: "This page isn't here. How about heading back to the homepage instead? It's nice there and there are lots of things to click on. If you think there is supposed to be something here that isn't let us know via the Issues page". I see that there is 60 bins programs, but I can't open and do anything with it. Please, help :)

**Comment by dermalplating** [comment] 2017-12-01 06:05
Hi dev team, same error for me. :)

**Comment by Utopiah** [comment] 2017-12-01 07:58
I'm assuming `xalosi/5/edit` instead of `https://jsbin.com/xalosi/5/edit` in the `My Bins` view.

![image](https://user-images.githubusercontent.com/1076655/33473133-854a5d84-d675-11e7-8840-31a5d3730405.png)

**Comment by remy** [comment] 2017-12-01 08:12
"Hey dev team" - this is me. I'm 100% jsbin and there's no one else. Just a reminder.

I'll fix this later today (8am atm).

**Comment by remy** [comment] 2017-12-01 08:13
Pretty sure this is the cause, triggering the URL to become absolute: https://github.com/jsbin/jsbin/commit/170ad3d169d8e8116d3aed950c1c06f074eff1a1#r25974640

**Comment by remy** [comment] 2017-12-01 08:34
Fixed in live.

**Closed by remy** 2017-12-01 08:34 UTC

**Comment by dermalplating** [comment] 2017-12-02 12:08
Thank you!



Sent from my Samsung device


-------- Original message --------
