### ISSUE TITLE
Login With Github Not Working

### ISSUE THREAD

**Issue by lunedam-git** [jsbin/jsbin#3048] opened 2017-05-12 15:30 UTC
Cannot login with Github.

Was fine yesterday, but today if I try to login via Github I just get returned to the login screen.

Can see JSBin as an authorised app in my Github and have tried clearing all cookies from my browser (Chrome 58) to no avail ...

**Comment by Imcolorpalette** [comment] 2017-05-12 16:13
It's not working for me either.

**Comment by davidakoch** [comment] 2017-05-12 17:36
Having same issue

**Comment by ethanhulse** [comment] 2017-05-12 18:09
Having same problems

**Comment by remy** [comment] 2017-05-12 19:09
I'm closing this as a dupe of #3045 which is essentially the same root cause.

**Closed by remy** 2017-05-12 19:09 UTC
