### ISSUE TITLE
URLs in bin view are wrong... add'l slash

### ISSUE THREAD

**Issue by pfoser** [jsbin/jsbin#3159] opened 2017-11-30 16:48 UTC
The links in the bin list have an add'l slash, e.g., http://jsbin.com**//**sdfsds

**Comment by remy** [comment] 2017-12-01 07:25
Can I get a screenshot? I'm not sure what the "bin view" is.

**Comment by Utopiah** [comment] 2017-12-01 07:57
I'm assuming `xalosi/5/edit` instead of `https://jsbin.com/xalosi/5/edit` in the `My Bins` view.

![image](https://user-images.githubusercontent.com/1076655/33473133-854a5d84-d675-11e7-8840-31a5d3730405.png)

**Comment by remy** [comment] 2017-12-01 08:12
Closing as dupe of #3160.

**Closed by remy** 2017-12-01 08:12 UTC
