### ISSUE TITLE
the editor windows always say "Processor"

### ISSUE THREAD

**Issue by ipodlover3354** [jsbin/jsbin#2847] opened 2016-08-15 12:52 UTC
`<a href="#htmlprocessors" role="menuitem" class="fake-dropdown button-dropdown">Processor</a>`

shouldn't it say "HTML" like usually does?

**Comment by remy** [comment] 2016-08-15 13:06
Dupe of #2843. The code was changed, but please do chime in on the current open issue.

**Closed by remy** 2016-08-15 13:06 UTC
